// Code generated by MockGen. DO NOT EDIT.
// Source: api/repository/setlist_repository.go
//
// Generated by this command:
//
//	mockgen -source=api/repository/setlist_repository.go -destination=api/repository/mocks/setlist_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	model "setlist/api/model"
	repository "setlist/api/repository"

	v5 "github.com/jackc/pgx/v5"
	pgconn "github.com/jackc/pgx/v5/pgconn"
	pgxpool "github.com/jackc/pgx/v5/pgxpool"
	gomock "go.uber.org/mock/gomock"
)

// MockDBTX is a mock of DBTX interface.
type MockDBTX struct {
	ctrl     *gomock.Controller
	recorder *MockDBTXMockRecorder
	isgomock struct{}
}

// MockDBTXMockRecorder is the mock recorder for MockDBTX.
type MockDBTXMockRecorder struct {
	mock *MockDBTX
}

// NewMockDBTX creates a new mock instance.
func NewMockDBTX(ctrl *gomock.Controller) *MockDBTX {
	mock := &MockDBTX{ctrl: ctrl}
	mock.recorder = &MockDBTXMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDBTX) EXPECT() *MockDBTXMockRecorder {
	return m.recorder
}

// CopyFrom mocks base method.
func (m *MockDBTX) CopyFrom(arg0 context.Context, arg1 v5.Identifier, arg2 []string, arg3 v5.CopyFromSource) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CopyFrom", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CopyFrom indicates an expected call of CopyFrom.
func (mr *MockDBTXMockRecorder) CopyFrom(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CopyFrom", reflect.TypeOf((*MockDBTX)(nil).CopyFrom), arg0, arg1, arg2, arg3)
}

// Exec mocks base method.
func (m *MockDBTX) Exec(arg0 context.Context, arg1 string, arg2 ...any) (pgconn.CommandTag, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Exec", varargs...)
	ret0, _ := ret[0].(pgconn.CommandTag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exec indicates an expected call of Exec.
func (mr *MockDBTXMockRecorder) Exec(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*MockDBTX)(nil).Exec), varargs...)
}

// Query mocks base method.
func (m *MockDBTX) Query(arg0 context.Context, arg1 string, arg2 ...any) (v5.Rows, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Query", varargs...)
	ret0, _ := ret[0].(v5.Rows)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockDBTXMockRecorder) Query(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockDBTX)(nil).Query), varargs...)
}

// QueryRow mocks base method.
func (m *MockDBTX) QueryRow(arg0 context.Context, arg1 string, arg2 ...any) v5.Row {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QueryRow", varargs...)
	ret0, _ := ret[0].(v5.Row)
	return ret0
}

// QueryRow indicates an expected call of QueryRow.
func (mr *MockDBTXMockRecorder) QueryRow(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryRow", reflect.TypeOf((*MockDBTX)(nil).QueryRow), varargs...)
}

// MockSetlistRepository is a mock of SetlistRepository interface.
type MockSetlistRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSetlistRepositoryMockRecorder
	isgomock struct{}
}

// MockSetlistRepositoryMockRecorder is the mock recorder for MockSetlistRepository.
type MockSetlistRepositoryMockRecorder struct {
	mock *MockSetlistRepository
}

// NewMockSetlistRepository creates a new mock instance.
func NewMockSetlistRepository(ctrl *gomock.Controller) *MockSetlistRepository {
	mock := &MockSetlistRepository{ctrl: ctrl}
	mock.recorder = &MockSetlistRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSetlistRepository) EXPECT() *MockSetlistRepositoryMockRecorder {
	return m.recorder
}

// AddItemToSetlist mocks base method.
func (m *MockSetlistRepository) AddItemToSetlist(ctx context.Context, item model.SetlistItem) (model.SetlistItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddItemToSetlist", ctx, item)
	ret0, _ := ret[0].(model.SetlistItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddItemToSetlist indicates an expected call of AddItemToSetlist.
func (mr *MockSetlistRepositoryMockRecorder) AddItemToSetlist(ctx, item any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddItemToSetlist", reflect.TypeOf((*MockSetlistRepository)(nil).AddItemToSetlist), ctx, item)
}

// BeginTx mocks base method.
func (m *MockSetlistRepository) BeginTx(ctx context.Context) (v5.Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTx", ctx)
	ret0, _ := ret[0].(v5.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginTx indicates an expected call of BeginTx.
func (mr *MockSetlistRepositoryMockRecorder) BeginTx(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTx", reflect.TypeOf((*MockSetlistRepository)(nil).BeginTx), ctx)
}

// CopyItemsToNewSetlist mocks base method.
func (m *MockSetlistRepository) CopyItemsToNewSetlist(ctx context.Context, tx repository.DBTX, newSetlistID int, items []model.SetlistItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CopyItemsToNewSetlist", ctx, tx, newSetlistID, items)
	ret0, _ := ret[0].(error)
	return ret0
}

// CopyItemsToNewSetlist indicates an expected call of CopyItemsToNewSetlist.
func (mr *MockSetlistRepositoryMockRecorder) CopyItemsToNewSetlist(ctx, tx, newSetlistID, items any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CopyItemsToNewSetlist", reflect.TypeOf((*MockSetlistRepository)(nil).CopyItemsToNewSetlist), ctx, tx, newSetlistID, items)
}

// CreateSetlist mocks base method.
func (m *MockSetlistRepository) CreateSetlist(ctx context.Context, db repository.DBTX, name, color string, bandID int) (model.Setlist, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSetlist", ctx, db, name, color, bandID)
	ret0, _ := ret[0].(model.Setlist)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSetlist indicates an expected call of CreateSetlist.
func (mr *MockSetlistRepositoryMockRecorder) CreateSetlist(ctx, db, name, color, bandID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSetlist", reflect.TypeOf((*MockSetlistRepository)(nil).CreateSetlist), ctx, db, name, color, bandID)
}

// DeleteSetlist mocks base method.
func (m *MockSetlistRepository) DeleteSetlist(ctx context.Context, setlistID, bandID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSetlist", ctx, setlistID, bandID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSetlist indicates an expected call of DeleteSetlist.
func (mr *MockSetlistRepositoryMockRecorder) DeleteSetlist(ctx, setlistID, bandID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSetlist", reflect.TypeOf((*MockSetlistRepository)(nil).DeleteSetlist), ctx, setlistID, bandID)
}

// DeleteSetlistItem mocks base method.
func (m *MockSetlistRepository) DeleteSetlistItem(ctx context.Context, itemID, bandID int) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSetlistItem", ctx, itemID, bandID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteSetlistItem indicates an expected call of DeleteSetlistItem.
func (mr *MockSetlistRepositoryMockRecorder) DeleteSetlistItem(ctx, itemID, bandID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSetlistItem", reflect.TypeOf((*MockSetlistRepository)(nil).DeleteSetlistItem), ctx, itemID, bandID)
}

// GetDB mocks base method.
func (m *MockSetlistRepository) GetDB() *pgxpool.Pool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDB")
	ret0, _ := ret[0].(*pgxpool.Pool)
	return ret0
}

// GetDB indicates an expected call of GetDB.
func (mr *MockSetlistRepositoryMockRecorder) GetDB() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDB", reflect.TypeOf((*MockSetlistRepository)(nil).GetDB))
}

// GetSetlistByID mocks base method.
func (m *MockSetlistRepository) GetSetlistByID(ctx context.Context, id, bandID int) (model.Setlist, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSetlistByID", ctx, id, bandID)
	ret0, _ := ret[0].(model.Setlist)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSetlistByID indicates an expected call of GetSetlistByID.
func (mr *MockSetlistRepositoryMockRecorder) GetSetlistByID(ctx, id, bandID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSetlistByID", reflect.TypeOf((*MockSetlistRepository)(nil).GetSetlistByID), ctx, id, bandID)
}

// GetSetlistItemsBySetlistID mocks base method.
func (m *MockSetlistRepository) GetSetlistItemsBySetlistID(ctx context.Context, setlistID int) ([]model.SetlistItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSetlistItemsBySetlistID", ctx, setlistID)
	ret0, _ := ret[0].([]model.SetlistItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSetlistItemsBySetlistID indicates an expected call of GetSetlistItemsBySetlistID.
func (mr *MockSetlistRepositoryMockRecorder) GetSetlistItemsBySetlistID(ctx, setlistID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSetlistItemsBySetlistID", reflect.TypeOf((*MockSetlistRepository)(nil).GetSetlistItemsBySetlistID), ctx, setlistID)
}

// GetSetlistsByBandID mocks base method.
func (m *MockSetlistRepository) GetSetlistsByBandID(ctx context.Context, bandID int) ([]model.Setlist, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSetlistsByBandID", ctx, bandID)
	ret0, _ := ret[0].([]model.Setlist)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSetlistsByBandID indicates an expected call of GetSetlistsByBandID.
func (mr *MockSetlistRepositoryMockRecorder) GetSetlistsByBandID(ctx, bandID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSetlistsByBandID", reflect.TypeOf((*MockSetlistRepository)(nil).GetSetlistsByBandID), ctx, bandID)
}

// UpdateItemOrder mocks base method.
func (m *MockSetlistRepository) UpdateItemOrder(ctx context.Context, setlistID int, itemIDs []int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateItemOrder", ctx, setlistID, itemIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateItemOrder indicates an expected call of UpdateItemOrder.
func (mr *MockSetlistRepositoryMockRecorder) UpdateItemOrder(ctx, setlistID, itemIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateItemOrder", reflect.TypeOf((*MockSetlistRepository)(nil).UpdateItemOrder), ctx, setlistID, itemIDs)
}

// UpdateSetlist mocks base method.
func (m *MockSetlistRepository) UpdateSetlist(ctx context.Context, setlist model.Setlist) (model.Setlist, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSetlist", ctx, setlist)
	ret0, _ := ret[0].(model.Setlist)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSetlist indicates an expected call of UpdateSetlist.
func (mr *MockSetlistRepositoryMockRecorder) UpdateSetlist(ctx, setlist any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSetlist", reflect.TypeOf((*MockSetlistRepository)(nil).UpdateSetlist), ctx, setlist)
}

// UpdateSetlistItem mocks base method.
func (m *MockSetlistRepository) UpdateSetlistItem(ctx context.Context, itemID, bandID int, notes *string) (model.SetlistItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSetlistItem", ctx, itemID, bandID, notes)
	ret0, _ := ret[0].(model.SetlistItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSetlistItem indicates an expected call of UpdateSetlistItem.
func (mr *MockSetlistRepositoryMockRecorder) UpdateSetlistItem(ctx, itemID, bandID, notes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSetlistItem", reflect.TypeOf((*MockSetlistRepository)(nil).UpdateSetlistItem), ctx, itemID, bandID, notes)
}
