// Code generated by MockGen. DO NOT EDIT.
// Source: api/repository/user_repository.go
//
// Generated by this command:
//
//	mockgen -source=api/repository/user_repository.go -destination=api/repository/mocks/user_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	model "setlist/api/model"

	gomock "go.uber.org/mock/gomock"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
	isgomock struct{}
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// AddUserToBand mocks base method.
func (m *MockUserRepository) AddUserToBand(ctx context.Context, userID, bandID int, role string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddUserToBand", ctx, userID, bandID, role)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddUserToBand indicates an expected call of AddUserToBand.
func (mr *MockUserRepositoryMockRecorder) AddUserToBand(ctx, userID, bandID, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUserToBand", reflect.TypeOf((*MockUserRepository)(nil).AddUserToBand), ctx, userID, bandID, role)
}

// GetAdminCountInBand mocks base method.
func (m *MockUserRepository) GetAdminCountInBand(ctx context.Context, bandID int) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAdminCountInBand", ctx, bandID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAdminCountInBand indicates an expected call of GetAdminCountInBand.
func (mr *MockUserRepositoryMockRecorder) GetAdminCountInBand(ctx, bandID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAdminCountInBand", reflect.TypeOf((*MockUserRepository)(nil).GetAdminCountInBand), ctx, bandID)
}

// CreateBandAndUser mocks base method.
func (m *MockUserRepository) CreateBandAndUser(ctx context.Context, bandName, username, passwordHash string) (model.User, model.Band, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBandAndUser", ctx, bandName, username, passwordHash)
	ret0, _ := ret[0].(model.User)
	ret1, _ := ret[1].(model.Band)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateBandAndUser indicates an expected call of CreateBandAndUser.
func (mr *MockUserRepositoryMockRecorder) CreateBandAndUser(ctx, bandName, username, passwordHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBandAndUser", reflect.TypeOf((*MockUserRepository)(nil).CreateBandAndUser), ctx, bandName, username, passwordHash)
}

// CreateUser mocks base method.
func (m *MockUserRepository) CreateUser(ctx context.Context, username, passwordHash string) (model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, username, passwordHash)
	ret0, _ := ret[0].(model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUserRepositoryMockRecorder) CreateUser(ctx, username, passwordHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUserRepository)(nil).CreateUser), ctx, username, passwordHash)
}

// CreateBand mocks base method.
func (m *MockUserRepository) CreateBand(ctx context.Context, name string, ownerUserID int) (model.Band, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBand", ctx, name, ownerUserID)
	ret0, _ := ret[0].(model.Band)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBand indicates an expected call of CreateBand.
func (mr *MockUserRepositoryMockRecorder) CreateBand(ctx, name, ownerUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBand", reflect.TypeOf((*MockUserRepository)(nil).CreateBand), ctx, name, ownerUserID)
}

// FindBandsWithRoleByUserID mocks base method.
func (m *MockUserRepository) FindBandsWithRoleByUserID(ctx context.Context, userID int) ([]model.BandWithRole, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindBandsWithRoleByUserID", ctx, userID)
	ret0, _ := ret[0].([]model.BandWithRole)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindBandsWithRoleByUserID indicates an expected call of FindBandsWithRoleByUserID.
func (mr *MockUserRepositoryMockRecorder) FindBandsWithRoleByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindBandsWithRoleByUserID", reflect.TypeOf((*MockUserRepository)(nil).FindBandsWithRoleByUserID), ctx, userID)
}

// CreateUserAndAddToBand mocks base method.
func (m *MockUserRepository) CreateUserAndAddToBand(ctx context.Context, bandID int, username, passwordHash, role string) (model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUserAndAddToBand", ctx, bandID, username, passwordHash, role)
	ret0, _ := ret[0].(model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUserAndAddToBand indicates an expected call of CreateUserAndAddToBand.
func (mr *MockUserRepositoryMockRecorder) CreateUserAndAddToBand(ctx, bandID, username, passwordHash, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUserAndAddToBand", reflect.TypeOf((*MockUserRepository)(nil).CreateUserAndAddToBand), ctx, bandID, username, passwordHash, role)
}

// FindBandsByUserID mocks base method.
func (m *MockUserRepository) FindBandsByUserID(ctx context.Context, userID int) ([]model.Band, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindBandsByUserID", ctx, userID)
	ret0, _ := ret[0].([]model.Band)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindBandsByUserID indicates an expected call of FindBandsByUserID.
func (mr *MockUserRepositoryMockRecorder) FindBandsByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindBandsByUserID", reflect.TypeOf((*MockUserRepository)(nil).FindBandsByUserID), ctx, userID)
}

// FindUserByID mocks base method.
func (m *MockUserRepository) FindUserByID(ctx context.Context, id int) (model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserByID", ctx, id)
	ret0, _ := ret[0].(model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUserByID indicates an expected call of FindUserByID.
func (mr *MockUserRepositoryMockRecorder) FindUserByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserByID", reflect.TypeOf((*MockUserRepository)(nil).FindUserByID), ctx, id)
}

// FindUserByUsername mocks base method.
func (m *MockUserRepository) FindUserByUsername(ctx context.Context, username string) (model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserByUsername", ctx, username)
	ret0, _ := ret[0].(model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUserByUsername indicates an expected call of FindUserByUsername.
func (mr *MockUserRepositoryMockRecorder) FindUserByUsername(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserByUsername", reflect.TypeOf((*MockUserRepository)(nil).FindUserByUsername), ctx, username)
}

// GetMembersByBandID mocks base method.
func (m *MockUserRepository) GetMembersByBandID(ctx context.Context, bandID int) ([]model.BandMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMembersByBandID", ctx, bandID)
	ret0, _ := ret[0].([]model.BandMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMembersByBandID indicates an expected call of GetMembersByBandID.
func (mr *MockUserRepositoryMockRecorder) GetMembersByBandID(ctx, bandID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMembersByBandID", reflect.TypeOf((*MockUserRepository)(nil).GetMembersByBandID), ctx, bandID)
}

// GetUserRoleInBand mocks base method.
func (m *MockUserRepository) GetUserRoleInBand(ctx context.Context, userID, bandID int) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserRoleInBand", ctx, userID, bandID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserRoleInBand indicates an expected call of GetUserRoleInBand.
func (mr *MockUserRepositoryMockRecorder) GetUserRoleInBand(ctx, userID, bandID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserRoleInBand", reflect.TypeOf((*MockUserRepository)(nil).GetUserRoleInBand), ctx, userID, bandID)
}

// IsUserInBand mocks base method.
func (m *MockUserRepository) IsUserInBand(ctx context.Context, userID, bandID int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsUserInBand", ctx, userID, bandID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsUserInBand indicates an expected call of IsUserInBand.
func (mr *MockUserRepositoryMockRecorder) IsUserInBand(ctx, userID, bandID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsUserInBand", reflect.TypeOf((*MockUserRepository)(nil).IsUserInBand), ctx, userID, bandID)
}

// RemoveUserFromBand mocks base method.
func (m *MockUserRepository) RemoveUserFromBand(ctx context.Context, bandID, userID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveUserFromBand", ctx, bandID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveUserFromBand indicates an expected call of RemoveUserFromBand.
func (mr *MockUserRepositoryMockRecorder) RemoveUserFromBand(ctx, bandID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveUserFromBand", reflect.TypeOf((*MockUserRepository)(nil).RemoveUserFromBand), ctx, bandID, userID)
}

// SetDefaultBand mocks base method.
func (m *MockUserRepository) SetDefaultBand(ctx context.Context, userID, bandID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetDefaultBand", ctx, userID, bandID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetDefaultBand indicates an expected call of SetDefaultBand.
func (mr *MockUserRepositoryMockRecorder) SetDefaultBand(ctx, userID, bandID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDefaultBand", reflect.TypeOf((*MockUserRepository)(nil).SetDefaultBand), ctx, userID, bandID)
}

// UpdatePassword mocks base method.
func (m *MockUserRepository) UpdatePassword(ctx context.Context, userID int, newHash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePassword", ctx, userID, newHash)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePassword indicates an expected call of UpdatePassword.
func (mr *MockUserRepositoryMockRecorder) UpdatePassword(ctx, userID, newHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePassword", reflect.TypeOf((*MockUserRepository)(nil).UpdatePassword), ctx, userID, newHash)
}
